import os
import sys
# Unfortunate Circumstances

P = ("Press Enter :")

#Title
print()
print()
print("*Unfortunate Circumstances*")
print()
print()

# Prologue/Introduction

# A brief explenation on the story. I kind of "disclaimer".
print("This story is about someone who, due to “Unfortunate Circumstances” gets forced to run away, get captured and hopefully escapes in the end. ")
print()
print("The story is based on a real experienced someone went through. ")
print("However, it is not exactly how it happened, Hence the “based” part. ")
print()
print("I hope you can enjoy the story as much I had fun making it.")
print()
input(P)
print()
print()
print()

# Questions, so that the experience can be more personal. 
print("What is your first name? ...")
Fname = input()
print()

print("What is your surname? ...")
Sname = input()
print()

print(f"{Fname} {Sname}. Good name. I like it")
print()
input(P)
print()

print("Now for your age, not that it matters much. they don't much care for age")
age = input()
print()

print(f"{age}? You must look wonderful at that age. Non the matter. Let's continue on")
print()
input(P)
print()

# Brief Sinopsis on the story itself and not behind the scenes stuff
print()
print("This is going to be about you. An Iranian citizen. ")
print()
input(P)
print()
print("As you are going through life, living it the best you can. ")
print()
input(P)
print()
print("But after tensions rise, and people start to drift apart. ")
print()
input(P)
print()
print("You get caught up in a situation that will change your life forever. ")
print()
input(P)
print()
print("In this story you will have to make a few choices. ")
print()
input(P)
print()
print("These choices matter, so take the time to think before you act.")
print()
input(P)
print()
print("Good luck")
print()
input(P)
print()


print("*The bad days to come, Act 1*")
print()
print()
input(P)

print("You wake up in bed. Checking the calendar to see what the date is, Monday the 16th of March 1998. A school day. ")
print()
input(P)
print()

print("“Another boring school day” you think. You get out of bed, have breakfast, get dressed and get ready for school.")
print("Just as you pack the last couple of books, your landline starts to ring.")
print()
input(P)
print()

print("After picking up, the good news fills you with joy. School is cancelled for the day,")
print("due to a routine check for any “traitors” hiding around. ")
print()
input(P)
print()

print("Your house had been ransacked a few days ago too. So, it was only a matter of time before they would check the school. ")
print()
input(P)
print()

print("You wonder whether your friends are out in town. So instead of grabbing your school bag you grab your wallet and go out the door, locking it behind you.")
print()
input(P)
print()

print("You look up and down your street. The streets were deserted, the sky was clear with a lovely blue hue. ")
print()
input(P)
print()

print("As you walk into town you ponder on why so little people are out today. It is usually quite busy on Monday.")
print("You see some of your friends hanging out on a bench. You join them")
print()
input(P)
print()

print()
print()
print()
print("*Later that day*")
print()
print()
print()
input(P)
print()
print()

print("You had lost track of time when you got home as the stars that filled the sky glistened with their beauty.")
print("Getting inside you realised you were hungry. ")
print()
input(P)
print()

print("Luckily, there was some microwave food in the fridge. You heated it up and had your dinner.")
print()
input(P)
print()

print("As you ate you dreamed about having proper dinners, a proper kitchen, more than 1 outlet.")
print("Living a life that’s better than now.")
print()
input(P)
print()

print("Like the people you read about in the library books. The people you see on the magazines. They look like they’re living the dream, and you wanted to join them. ")
print()
input(P)
print()

print("As the night went on you got more tired, and tired, and tired until you eventually fell asleep. ")
print()
input(P)
print()

print("As you slept you dreamed about having a proper house, a loving family, good food. Everything a good life needs. ")
print()
input(P)
print()

print("You wake up to the news that school was on again. You winsed as you heard the news.")
print("But luckily you didn’t have to prepare your bag as you’d done that yesterday.")
print("You stepped outside and where surprised by the amount of people walking around.")
print("However most where walking in one direction, away from town. They seemed to have packed stuff with them. ")
print()
input(P)
print()

print("You payed them no mind as you continue to walk to school.")
print("Once at school you are greeted by two soldiers who ask what class you belong too.") 
print("You tell them and they take you to it. You see some of your classmates and your best friend sitting in there. ")
print("Aswell as your teacher, sitting at his desk. ")
print("The silence was deafening. No one spoke a word, and everyone seemed worried or distressed.") 
print("You didn’t understand why but went along with it so you wouldn’t stand out.")
print()
input(P)
print()

print("As time went on more and more of your classmates came in, escorted by the two soldiers at the gate. ")
print("Eventually everyone had entered on time. After around five minutes a man in a suit came in. ")
print("He was balding and looked at the class with a threatening expression.")
print("People started looking even more distressed and worried, and the slightest whispers could be heard ")
print()
input(P)
print()

print("The man in the suit let out a loud clap. And instantly everyone shut up and looked at him. ") 
print("“As you all may know, we ran a routine check yesterday”, he said slowly walking back and forth through the class. ")
print("“We do this to find any evidence of people who want to oppose our leader, which all of you know. ")
print("Has the penalty of jail time, and in some cases death. ")
print("When we went through this check yesterday, we were not expecting to find anything. Until we found this”. ")
print()
input(P)
print()

print("He held up a piece of paper that displayed a stamp of the UN. ")
print("It was a legal document to help the students get to a safe place. ")
print("“This was found in the principal’s office under a floorboard. ")
print("When we found it, we realised that this document must have gotten to him somehow. ")
print("We have already detained all suspects among the staff. However, we have not checked the students. ")
print("Because of this we will be confiscating your bags.” ")
print()
input(P)
print()

print("When he said this. Two different soldiers from before went to every student and grabbed their bag. ")
print("Including yours. You didn’t much care as you didn’t own anything that would deem you a suspect. ")
print("But it was scary to think that your principle is gone, or even dead. Just because he wanted to help the students.")
print()
input(P)
print()

print("After another few speeches about how great our leader is the soldiers came back and grabbed 3 students in total,") 
print("handcuffing them and taking them away. After they had gone the man in front of the class said:") 
print("“Well, because you don’t have a principle, and we’ve got what we wanted. We’ll let you go home.")
print("No need to come back for the week.")
print()
input(P)
print()

print("After saying this he left the room. Once he was gone you could see your teacher grab his bag and leave in a hurry. ")
print("We took this a sign to leave. We exited the school, some of the students waved at the soldiers. ")
print("You wanted to get home asap and finish your book. So, you went into the alley way to take the shortcut.")
print()
input(P)
print()

print("But as you walked through the alley you saw some soldiers in the back-apartment garden. ")
print("You hid behind the wall, looking while staying hidden. ")
print("You saw that the soldiers where positioning people with bags over their head against the wall, ")
print("and you knew exactly what was going to happen.")
print()
input(P)
print()

print("But before you could leave, you saw one of your friends next to one of the soldiers. ")
print("They were talking to one of them. ")
print("Not in objection however, he looked like he was admiring the soldiers, asking them questions.")
print("“When can I try shooting dad?” you could faintly hear him say.")
print()
input(P)
print()

print("However, while you were focusing on him being there, you saw that they had cocked their guns. ")
print("And they took the shot. ")
print("All three of the bagged people’s bodies hit the floor, and there where faint blood stains on the wall.") 
print("You gasped to what you just witnessed, and your friend noticed.")
print()
input(P)
print()

print("He looked around, and as he did you took your leave and ran back the way you came. ")
print("You heard him running far off behind you, however it seemed no matter which way you went, you couldn’t lose him.")
print()
input(P)
print()

print("Eventually you came up to a t split. But while you were deciding which way to go, he had caught up. ")
print("You looked him dead in the eye while he pointed the gun at you. ")
print()
input(P)
print()

print(f"“{Fname}? What the hell are you doing?” he said, putting the gun to his side. ")
print("“I wanted to take a shortcut home” You said, looking at him with disgust.")
print("“Don’t you think it’s great? Those people getting what they deserve”") 
print("He said this with such a happy expression, so confidently. ")
print()
input(P)
print()

print("Your face went pale. And you had a simple answer. “No, it isn’t. Those where innocent people!” ")
print("As you said this his smile started to fade. ")
print("“They were against our leader, they didn’t deserve to live!” He shouted. ")
print()
input(P)
print()

print("“Our leader doesn’t deserve to live!” you shouted back.") 
print("And as the words left your mouth, you realised what you’d said.") 
print("You shouldn’t have said that you shouldn’t have said that. It blared in your mind.")
print(" “then you’re part of the enemy.” He said slowly grabbing his sidearm again. ")
print()
input(P)
print()

print("What are you going to do? plead for mercy? or run? pick either: mercy or run")
answerD = input()
if answerD == 'run':
    print()
    print("Before he could shoot, you had realized he wasn’t going to stop. And you ran in the direction of mid-town.") 
    print("Once you arrived, the streets where starting to fill up with people who were leaving.")
    print()
elif answerD == 'mercy' :
    print()
    print("“I didn’t mean it, please” you screamed at him, tears in your eyes. ")
    print("“you said it, no going back (Name)” He said, holding the gun at you. ")
    print("Before you could react, he had pulled the trigger. The tears in your eyes stopped as you hit the ground. ")
    print("As you laid there you could see the lovely blue sky. Until the empty embrace of death swallows you whole. ")
    print("Bringing you to a bitter end.")
    print()
    input(P)
    print()
    print("ENDING D, SHOT")
    input("Press Enter to exit")
    exit()
else :
    print()
    print("You froze, not knowing what to do. As ypu realized this.") 
    print("He had already pulled the trigger, bringing you to a bitter end")
    print()
    input(P)
    print()
    print("ENDING D, SHOT")
    input("Press enter to exit")
    exit()

print()
input(P)
print()

print("So, you took advantage of the chaos and tried to get across.") 
print("While it was incredibly cramped, people weren’t in a hurry, so they were letting you through more.")
print("To combat the more aggressive folk you were walking at a slightly faster walking pace to avoid suspicion. ")
print()
input(P)
print()

print("As you got to the other side you looked at the sea of people to see if you could see him.") 
print("You could see a crowd of people circling around a fight between him and another guy. ")
print("You didn’t know the other guy, As you run in to help the stranger, ")
print("you see that your pursuer had dropped his gun on the ground. ")
print("You run over quickly to pick it up and…")
print()
input(P)
print()

print("shoot, or run?")
answerB = input()
if answerB == 'run' :
    print()
    print("You take the gun and run. Throwing it in a nearby trash can as you run away from the fight.")
    print()
elif answerB == 'shoot' :
    print()
    print("You shoot him. Ending the fight. Dropping the gun on the spot you run.")
    print()
else : 
    print()
    print("Somehow your friend got out of the stranger's grasp. He pounced you and grabbed the gun. Shooting you instantly.")
    print()
    input(P)
    print()
    print("ENDING E, FAILED TO ACT")
    print()
    input("Press Enter to exit")
    exit()

input(P)

print()

print("After running back home you got in as soon as possible. And barricaded yourself in your basement.") 
print("planning on leaving town in the morning. “What a shit day” You thought to yourself.")
print()
input(P)
print()
print()

print("*The day your world changed")
print()
print()
input(P)
print()

print("You woke up in your basement. You where snoozing first until you remembered what had happened the day before.")
print("As you were on the brink of teas, knowing you’re going to have to leave it all behind. You stopped to a sudden thud… ")
print()
input(P)
print()

print("Then another. And another. And then you realised. They were breaking in upstairs.") 
print("You grabbed your mattress and hid in the corner behind it. Hearing them break everything upstairs.") 
print("You knew this wasn’t a routine check. They were looking for you. ")
print()
input(P)
print()

print("Luckily, the basement door was under the carpe- BAM. The door opened. And the soldier came in.") 
print("“Come on out, we know you’re here. Don’t give us a reason to shoot”. The words sounded soothing. ")
print("Like a spec ops agent. But the tone he gave it made you freeze in fear. ")
print("Like you where going to die, behind a mattress. ")
print()
input(P)
print()

print("As you sat there anticipating the end. The mattress was raised, and the soldier forcefully grabbed you by the arm. ") 
print("Pulling you up. “MOVE!” He shouted, so loud that your ears where ringing. ")
print("But you didn’t have time to pay that mind. ")
print("You didn’t want to die.")
print()
input(P)
print()

print("So, you moved out of the house while being detained. He stood you in a line of a few dozen people. ")
print("And what looked like the lieutenant of the team started giving everyone a number, it was either 1 or 2.") 
print("As he got closer you kept getting redder, redder and redder.")
print()
input(P)
print()

print("When he finally got to you, he paid it no mind. “2” He said. Walking to the commanding officer. ")
print("The officer then stood in front of everyone in the line. And he shouted the number “1”. ")
print()
input(P)
print()

print("Then the soldiers standing guard grabbed the people with the number 1 and brought them into the outback alleyway. ")
print("While the rest of you were put into a large truck that was parked just down the road. In the heat of the moment you hadn’t seen it.")
print()
input(P)
print()

print(". It was cramped in the truck. While there was a bit of wiggle room. It was nowhere near comfortable. ")
print("And as you sat there in silence you saw that some of the people with you were young. scarily young. Hugging her mother.")
print()
input(P)
print()

print("At the sight you knew exactly that whatever was going to happen. It was going to be horrible. ")
print("After a few painful hours of driving, you arrived at facility.")
print()
input(P)
print()

print("But for the only few seconds you saw. You felt a bag being forcefully rammed over your head. ")
print("And with the hard ram you felt something hit your head hard. And you blacked out…")
print()
input(P)
print()


print()
print()
print("*The Prison, Act 2")
print()
print()
input(P)

print()

print("You woke up in a cell. When you woke up you sprung up, standing Immediately. The cell was small. ")
print("A single small bed, a toilet and a basic sink. The bed was about 1/3rd of the room. ")
print("So, wiggle room wasn’t much accessible. ")
print()
input(P)
print()

print("The cell was dirty and had only a single opening to the outside. Because while the room was small. ")
print("It was incredibly tall. ")
print("You estimated around 5 meters, ")
print("and at the around 4,5 mark there was a barred window letting in just enough light to have the cell not be dark.")
print()
input(P)
print()

print("After you had identified your surroundings, the weight of the situation had poured over you. ")
print("And you burst into tears.  Almost screaming. ")
print("This had apparently annoyed some guard, ")
print("because one came by and slammed their weapon against the bars of your cell. ")
print("The slamming immediately made you stop. “SHUT UP IN THERE” he proclaimed, shouting louder than you.")
print()
input(P)
print()

print("You didn’t say anything. Simply lying in your bed and thinking about what’s going to happen. ")
print("Are they going to kill you? Are they going to make you rot in this prison? ")
print("All the questions came streaming through your head for around 2 hours when a guard opened your cell.")
print()
input(P)
print()

print("“Food make a move, or you won’t have any” he said in an uncaring tone. ")
print("It didn’t matter much as at the word food you had already jumped up and went out the open cell. ")
print("Looking around, you could see many other’s like you. ")
print()
input(P)
print()

print("Holding cells in a large room. All around. The prison seemed to have 3 floors. ")
print("However, at the end far end of the room you saw one big cell. ")
print("Filled with so many people that there was no way it could comfortably fit them all.")
print(" You guessed you where one of the lucky ones. Getting your own cell.")
print()
input(P)
print()

print("As you entered the “canteen”. You realised that that word doesn’t describe it properly. ")
print("You could equate it to a newly dug landfill. And it was disgusting. ")
print("There was, what you could only think was throw up and extraments on the ground. Disgusting. ")
print()
input(P)
print()

print("And what was it you where eating? Apparently, a mix of soy bread and an unknown paste.") 
print("While to your relief, it didn’t taste foul. It didn’t taste of everything. ")
print("So, this wasn’t much going to give you a reason to eat.")
print()
input(P)
print()

print("Afterwards you apparently had an hour of courtyard time. ")
print("This sounded quite nice to you as you wanted to see what outside looked like. ")
print("While the courtyard was full of people,")
print("you had realised that there was a mildly empty space on a single bench near the gate. ")
print("You went and sat down. Looking at the nearby trees. Sealing you off from the rest of the world. ")
print("No one to hear you. No one to listen. Just you and this mistake of a place.")
print()
input(P)
print()

print("When you woke up the next morning, the dread of this new routine hit you. ")
print("You wanted to return to your old life. The one with friends, school and the ounce of freedom you had. ")
print("Now you where alone. You knew no one. And you where scared. ")
print()
input(P)
print()

print("But you didn’t lose hope. While the conflict rises outside. ")
print("The not that was given to your principle by the UN gave you hope. Someone cares about your freedom. ")
print("And you where hoping they would find this place, and free all of you. ")
print("This single ounce of hope gave you enough willpower to keep going")
print()
input(P)
print()

print("And so, you did. For a week you went through the same, monotonous routine. However. ")
print("One day in the courtyard something horrible happened.")
print()
input(P)
print()

print(". A male prisoner was assaulting a woman. ")
print("The same woman with the child you saw in the truck that brought you here. ")
print("At the sight of this you where wondering if anyone was going to do anything. ")
print("But before anything did. Guards had grabbed both. And where bringing them away. ")
print()
input(P)
print()

print("Her child started crying, in the middle of the courtyard. Calling for her mom. ")
print("The noise she made could be heard all around the courtyard. ")
print("But no one was paying attention to her. You wanted to do something. ")
print("You wanted to comfort her. ")
print("But before you could, another guard had grabbed the little girl and forcefully pulled her away. ")
print("Their fate? You didn’t know, and you didn’t want to think about it. ")
print()
input(P)
print()

print("The thought of them killing her nearly made you throw up. And later in your cell you did. ")
print("In the toilet. Luckily, this place had some plumbing. So, you were able to flush. ")
print("The quality of the water was questionable, however.  ")
print("It tasted of nickle. Which you didn’t think was a good sign. So you only drank sparingly.")
print()
input(P)
print()

print("As the weeks turned into a month. The routine became your new lifestyle. ")
print("Wasting away with your thoughts. You got sick for a week, and no one cared. ")
print("But, once a week. Everyone can have night-time courtyard time. ")
print("And you heard that There wasn’t as much security during this non curfew day. ")
print("And for this week. You wanted to join in. ")
print()
input(P)
print()

print("Friday came. And it was night-time courtyard day. ")
print("You asked one of the guards to escort you there, which he did. ")
print("After arrival you saw some other inmates around a fire.") 
print("This fire normal for the occasion. ")
print("You knew because you could always see the light of the fire on Friday through your barred window.")
print()
input(P)
print()

print(". As you approached you could already hear them talking about stuff. ")
print("You sat down next to a man with a bandage over his left eye. ")
print("And a woman who seemed to have lost her right thumb. ")
print("A lot of them where older. And they asked who you were. You replied: ")
print()
input(P)
print()

print(f"My name is {Fname} {Sname}. {age}")
print()
input(P)
print()
print(f"Whatcha in for {Fname}?")
print()
input(P)
print()

if answerB == 'shoot' :
    print("“Killed an old friend. He wanted to kill me because I said our “leader” didn’t deserve to live.’’ you said. ")
    print()
    input(P)
    print()
elif answerB == 'run' :
    print("“I slagged off our leader, and now I’m here”")
    print()
    input(P)
    print()
else:
    print()

print("Silence fell among the group when you said it. ")
print("To break the ice you said “So, what are you guys in for?”  ")
print()
input(P)
print()

print("The first one to speak was a young man, around 21 years old. He stood up and spoke.")
print("“I was apprehended for being near apparent spies. ")
print("I was simply walking down the street and they grabbed everyone there and interrogated them. ")
print("However, when they found the spies, they didn’t even let the rest of us go. ")
print("They simply threw us in another truck and sent us here.” He said in a depressing tone.")
print()
input(P)
print()

print("Such a simple thing. ")
print("Walking down the street can get you locked up if you so happen to be there at the wrong time. ")
print("A woman spoke. “I had a similar situation. My son worked for one of the last pharmacies in area. ")
print("He was apparently. selling medicine to the enemy.” She said. Seemingly in tears.")
print()
input(P)
print()

print("“What happened to get you in here?” said the old man next to you. ")
print("“He was caught doing it, and he was being escorted to be executed. ")
print("I saw him.. being..” she cried. “if it hurts to talk about, you don’t have to” The old man said. ")
print("Holding up his hand for her to stop. “Thank you” she said in return. ")
print()
input(P)
print()

print("The old man then spoke. “I’ve been here since forever. I am the father of the warden. ")
print("He’s a firm believer that our leader is basically god. He won’t shut up about him. ")
print("And one day I told him to stop obsessing. And on that word, he immediately had me sent here. ")
print("His own father. I was heartbroken. I’ve tried many times to escape. ")
print("Tried over that fence around three months ago.")
print()
print(P)
print()

print("Although I fell halfway through the climb and list my eye to a branch. ")
print("They could only find a bandage for it. Still stings a bit.” ")
print("After hearing this story, you asked why he was never taken to be executed. ")
print("“The warden gives those orders. And while I’ve been brought to him many a time. ")
print("It brings me joy seeing that look in his eye. He can’t bring himself to order me an execution.”")
print()
input(P)
print()

print("The woman next to you spoke up just after. ")
print("“Did you all hear that we’ll be getting a psychological test in August?” she said. ")
print("“That comes every year. Not much happens but a few questions. ")
print("They do it to keep an eye on everyone’s mental state” The old man says. ")
print("Before anyone else could tell their story however, everyone was instructed to go back to their cells. ")
print("And they did. ")
print()
input(P)
print()

print("The weeks turned into months. ")
print("People were starting to be executed in rounds, without having done anything wrong. ")
print("You where scared for your life. But a little relief was that the psychiatry session was coming soon. ")
print()
input(P)
print()

print("It was apparently a little early as the old psychiatrist wasn’t available. ")
print("The day came and everyone had a turn until you where picked up and brought to the room. ")
print("There was a woman inside. In her 40s. ")
print()
input(P)
print()

print("‘’Come, sit” she said, pointing to the chair at the other side of the single table. ")
print("She had three pieces of paper. One with information about you. ")
print("One with questions, a pen and some blank paper. ")
print()
input(P)
print()

print(f"‘’{Fname}. You’ve been here for around six months now. ")
print("I’m the psychiatrist who checks on the inmates’ mental state. ")
print("I want to ask some questions.” She said in a comforting soft tone. ")
print("You simply nodded.")
print()
input(P)
print()

print("“How would you say it has been here? A, bad? B, no opinion? C, Good?”")
questionCA = input()

print()
print()

print("“If you could leave this place right now and go anywhere you want? ")
print("Where would you go? A, stay in this country? B, go to a different country? C, no comment?”")
questionCB = input()

print()
print()

print("“You said from our witness report team that you said our leader should perish. ")
print("Do you still believe in this statement? A, Yes. B, No.”")
questionCC = input()
if questionCC == 'A' :
    print()
    print("*She winks at you*")
    print()
    print()
else :
    print()


print(f"“Alright, thank you {Fname}. ")
print("I will be going now, I hope that you will find some happiness in this place” she said, ")
print("You didn’t question it and just simply went back to your cell. ")
print("While this experience was pleasant enough for you. Meeting someone who seems to care. ")
print("You just went back to bed. Hoping the results come back good.")
print()
input(P)
print()

print()
print()
print("*Results*")
print()
print()

print("The results where given to you in a letter by a guard.")
print()
input(P)
print()

if questionCA == 'B' and questionCB == 'C' and questionCC == 'B' :
    print("After you read the results you see a stamp on the bottom, positive. ")
    print("Afterwards the guard grabs your arm and forcefully escorts you into a van, ")
    print("the van taking you and 3 others to another facility. ")
    print("Once you arived you realised, this is a psychiatric hospital. ")
    print("And you knew you were never leaving again ")
    print()
    input(P)
    print()
    print("ENDING C, INSANE AND DETAINED")
    input(P)
    print()
    print("Press Enter to exit")
    exit()
else :
    print("You read the note with your results and you see a stamp on the bottom. Negative. ")
    print("Afterwards the guard takes the results and the envelope and closes the cell. ")
    print("Leaving you inside.")
    print()
    input(P)
    print()

print("August the 2nd. You wake up to screaming. ")
print("People are being dragged away, and you see a guard coming for your cell. ")
print("You already knew what was going to happen. ")
print("As you get pulled out of your cell you think about what happened in your life. ")
print("And before you knew it. You where bagged and taken outside..")
print()
input(P)
print()

if answerB == 'shoot' :
    print("The guard takes you to the back of the facility, and it reaks of rotting flesh. ")
    print("They put you with your back away from the wall, ")
    print("and you feel a gun barrel rest on the back on your head.")
    print("After a few second, having your whole life flash before your eyes. You hear. 'FIRE'...")
    print("Without the gunshot. You felt yourself drift into the warm arms of death. Gone. Dead")
    print()
    input(P)
    print()
    print("ENDING B, EXECUTED")
    exit()
elif answerB == 'run' :
    print("After walking a ways away. You realise you're being walked out of the facility")
    print("Your bag gets taken off, and you see different looking soldiers than before. ")
    print("They wore blue helmets and has a UN symbol on their arm. Was it true? Had they come?")
    print("Yes, they have. And you where so happy. You where instructed to get in a van. ")
    print("And once you got in it was so much better than before. There where seats and window.")
    print("It wasn't cramped. ")
    print("With this sign of hope you where basically praying they would bring you to a better place.")
else:
    print()

print()
print()
input(P)
print()
print()
print("* Epilogue *")
print()
input(P)
print()
print()

print("You arrived in a truck. In front of another building. ")
print("But instead of it looking like a facility. It looked more like a Hospital or retirement home. ")
print("I was so happy to see it. I knew that I was safe. ")
print("A different country, different people. A new start. And I can’t wait. ")
print()
input(P)
print()

print("I entered the building with the rest of the people, I was instructed to sit at one of the tables. ")
print("I was relieved when I heard “May you please”. For once you weren’t forced. ")
print("You sat down and a young woman, in her mid-20s sat in front of you. ")
print()
input(P)
print()

print("“Hello, and welcome to the Netherlands.” For the first time in half a year. ")
print("You Where talking to an actual human being in power. She went through a basic survey. ")
print("Where did you come from? How long you where in there. Etc.")
print()
input(P)
print()

print("It was nice. You felt safe. You felt comfortable. “Thank you for answering the questions. ")
print("You will be given some legal documents,")
print("and you will be given a room to stay in for the time being.” She said with a smile. ")
print()
input(P)
print()

print("As she left a man came by and gave you a folder with a pen. ")
print("In the folder where questions on who you were. And what happened. ")
print("After writing down what you needed to you where given a key and directions to your room. no escort. ")
print("You went at your own leisure. ")
print()
input(P)
print()

print("Getting into your room you saw a bed, a desk, and a table with a tv on it. A tv.")
print("You didn’t even have that in your own home. ")
print("You knew when you went to sleep that night, that you where safe, ")
print("and that you were going to make the most of your life.  ")
print()
input(P)
print()

print()
print()
print()
print("When you woke up a letter was on your desk. Inside layed documents for a citizenship. ")
print("At the sight you were filled with joy. ")
print("You immediately filled out the documents and handed them in at the help desk. ")
print
input(P)
print()

print("Afterwards you where asked if you wanted to join everyone on going into town and seeing the sights. ")
print("Without hesitation the word yes came out of your mouth. ")
print("You went out in town. Seeing the shops. Seeing the people.")
print()
input(P)
print()

print("Everyone around seemed so friendly. ")
print("You where asking around where you where and people said you where in Utrecht. ")
print("In the end you didn’t really care. You where just happy you where free. ")
print()
input(P)
print()

print("Getting accustomed to this country, you where given classes on the language. ")
print("Learning Dutch was extremely difficult. ")
print("But you were eager to learn it, as you wanted to join this society as soon as possible.")
print("It only took a month, and you had the basics down. ")
print("And you where aloud to go out on your own. ")
print()
input(P)
print()

print("Soon came your first solicitation interview. ")
print("Then a job. And in 1999, on June 23rd you had your own apartment, with a job working in a bakery, ")
print("as you had found out you where quite good at it. ")
print("You live a happy life to this day, and you are happy you can live a good life. Correct?” The interview said, ")
print("he had been talking for a while.")
print()
input(P)
print()

print("“Yes, that is what happened.” You said. “I’m happy I understood what you meant.")
print("Now, as for the book. I want it to be clear that some changes will be names. ")
print("You did not give away names, and so I will be giving them myself. Is that alright?” ")
print("He asked in a respectful tone. ")
print()
input(P)
print()

print("“Yes, I didn’t give any names because I can’t remember them much. ")
print("I’ve been blacking out on this part of my life for a while now”. You said, explaining your reasoning too. ")
print()
input(P)
print()

print("You two shook hands and you went on your merry way. ")
print("A biography on your life was to come out in 2006, in about one year after the interview. ")
print("As for your life currently? ")
print()
input(P)
print()

print("Well. You own the bakery now. The owner became to old and gave it to you. ")
print()
input(P)
print()

print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print("Your experience has made you more thankfully for anything good that happens to you. ")
print("You now have friends, a good job, your own house and a happy attitude. ")
print()
print("You where happy. And you couldn’t wait for what the rest of your life has to offer. ")
print()
print("If you’ve gotten so far in the story. I would like to thank you personally. ")
print()
print("I’ve been quite passionate about this topic. ")
print("And I’ve always wanted to adapt someone’s story into something special. ")
print("And I hope you enjoyed it!")
print()
input(P)
print()
print()
print()
print("*ENDING A, A GOOD NEW LIFE*")
print()
input(f"Press enter to exit, thank you {Fname}")


